### ISSUE TITLE
SAML not working when flarum running in docker on different port

### ISSUE THREAD

**Issue by Kola50011** [askvortsov1/flarum-saml#9]
Hey there!

I am currently trying to integrate flarum with keycloak and tried this extension out. After configuring everything I get the error
`Could not process response: invalid_response: The response was received at http://xx.xx:8000/auth/saml/acs instead of https://xxx.xx/auth/saml/acs`

This problem arises, because I am running flarum inside a docker container running on port 8000 and remapping to 80. The https cert is also done somewhere else, which results in https instead of http before the url.

Is there any way to allow another url / change this check?
I can provide more information, if needed.

Best Regards

**Comment by askvortsov1** [comment]
Hi! I ran into this myself at some point, and was unable to find a good solution. I had to submit a PR to the library I was using at the time: https://github.com/mondediefr/docker-flarum/pull/45. Iirc, the saml2 library this ext uses gets port/url from globals, and there's no good place to override. Might be good to open an issue upstream.
